{
    "Hired Wrestlers": [
        "Brian Cage",
        "Ortiz",
        "Santana",
        "Tommy Dreamer",
        "Sami Callihan",
        "Ace Austin",
        "Alisha Edwards",
        "Cody Deaner",
        "Cousin Jake",
        "Daga",
        "Dave Crist",
        "Dez",
        "Eddie Edwards",
        "Ethan Page",
        "Fallah Bahh",
        "Jake Crist",
        "Johnny Impact",
        "Jordynne Grace",
        "Josh Alexander",
        "Kiera Hogan",
        "Killer Kross",
        "Kongo Kong",
        "Madison Rayne",
        "Madman Fulton",
        "Mahabali Shera",
        "Moose",
        "Petey Williams",
        "Raj Singh",
        "Rich Swann",
        "Rob Van Dam",
        "Rohit Raju",
        "Rosemary",
        "Su Yung",
        "Taya Valkyrie",
        "Tessa Blanchard",
        "Trey",
        "Willie Mack",
        "Wentz",
        "Eli Drake",
        "Glen Gilberti",
        "Jimmy Jacobs",
        "Michael Elgin",
        "Sabu",
        "The Sandman",
        "Scarlett Bordeaux",
        "Melissa Santos",
    ],
    "Male Ready Heels": ["Ortiz", "Santana"],
    "Male Ready Faces": [
        "Brian Cage",
        "Tommy Dreamer",
        "Ace Austin",
        "Cody Deaner",
        "Cousin Jake",
        "Daga",
        "Dez",
        "Eddie Edwards",
        "Fallah Bahh",
        "Petey Williams",
        "Rich Swann",
        "Trey",
        "Willie Mack",
        "Wentz",
        "Sabu",
        "The Sandman",
    ],
    "Male Ready Anti Heroes": [
        "Sami Callihan",
        "Dave Crist",
        "Ethan Page",
        "Jake Crist",
        "Johnny Impact",
        "Josh Alexander",
        "Killer Kross",
        "Kongo Kong",
        "Madman Fulton",
        "Mahabali Shera",
        "Moose",
        "Raj Singh",
        "Rob Van Dam",
        "Rohit Raju",
        "Eli Drake",
        "Glen Gilberti",
        "Jimmy Jacobs",
        "Michael Elgin",
    ],
    "Male Ready Tweeners": [],
    "Male Ready Jobbers": [],
    "Female Ready Heels": [],
    "Female Ready Faces": [
        "Alisha Edwards",
        "Jordynne Grace",
        "Rosemary",
        "Tessa Blanchard",
        "Scarlett Bordeaux",
        "Melissa Santos",
    ],
    "Female Ready Anti Heroes": [
        "Kiera Hogan",
        "Madison Rayne",
        "Su Yung",
        "Taya Valkyrie",
    ],
    "Female Ready Tweeners": [],
    "Female Ready Jobbers": [],
    "Tag Teams": [
        {"Tag Team": "Latin American Xchange", "Members": "Ortiz/Santana"},
        {"Tag Team": "", "Members": "Ortiz/Santana"},
        {"Tag Team": "Santana/Ortiz", "Members": "Ortiz/Santana"},
        {"Tag Team": "The Deaners", "Members": "Cody Deaner/Cousin Jake"},
        {"Tag Team": "", "Members": "Dave Crist/Jake Crist"},
        {"Tag Team": "The North", "Members": "Ethan Page/Josh Alexander"},
        {"Tag Team": "Monster Mafia", "Members": "Ethan Page/Josh Alexander"},
        {"Tag Team": "Jake Crist/Dave Crist", "Members": "Dave Crist/Jake Crist"},
        {"Tag Team": "", "Members": "Rob Van Dam/Sabu"},
        {"Tag Team": "Sabu/Rob Van Dam", "Members": "Rob Van Dam/Sabu"},
    ],
    "Hired Tag List": [
        "Latin American Xchange",
        "",
        "Santana/Ortiz",
        "The Deaners",
        "The North",
        "Monster Mafia",
        "Jake Crist/Dave Crist",
        "Sabu/Rob Van Dam",
    ],
    "Stables": [
        {
            "Stable Name": "The Desi Hit Squad",
            "Global Member Count": "3",
            "Member Ids": ["375", "378", "381", "22"],
            "Members": ["Mahabali Shera", "Raj Singh", "Rohit Raju"],
            "Hired Members": 3,
        },
        {
            "Stable Name": "The Rascalz",
            "Global Member Count": "3",
            "Member Ids": ["361", "386", "388"],
            "Members": ["Dez", "Trey", "Wentz"],
            "Hired Members": 3,
        },
        {
            "Stable Name": "oVe",
            "Global Member Count": "3",
            "Member Ids": ["360", "365", "374"],
            "Members": ["Dave Crist", "Jake Crist", "Madman Fulton"],
            "Hired Members": 3,
        },
    ],
    "Stable List": ["The Desi Hit Squad", "The Rascalz", "oVe"],
    "Stable Tags": [],
    "Stable Tags List": [],
    "injured names": [],
    "Eligible Roster": [
        "Brian Cage",
        "Ortiz",
        "Santana",
        "Tommy Dreamer",
        "Sami Callihan",
        "Ace Austin",
        "Alisha Edwards",
        "Cody Deaner",
        "Cousin Jake",
        "Daga",
        "Dave Crist",
        "Dez",
        "Eddie Edwards",
        "Ethan Page",
        "Fallah Bahh",
        "Jake Crist",
        "Johnny Impact",
        "Jordynne Grace",
        "Josh Alexander",
        "Kiera Hogan",
        "Killer Kross",
        "Kongo Kong",
        "Madison Rayne",
        "Madman Fulton",
        "Mahabali Shera",
        "Moose",
        "Petey Williams",
        "Raj Singh",
        "Rich Swann",
        "Rob Van Dam",
        "Rohit Raju",
        "Rosemary",
        "Su Yung",
        "Taya Valkyrie",
        "Tessa Blanchard",
        "Trey",
        "Willie Mack",
        "Wentz",
        "Eli Drake",
        "Glen Gilberti",
        "Jimmy Jacobs",
        "Michael Elgin",
        "Sabu",
        "The Sandman",
        "Scarlett Bordeaux",
        "Melissa Santos",
    ],
    "Busy Wrestlers": ["Santana"],
}
